name: Deploy DockiShip Backend (PM2) — simple pull & restart

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: deploy-dockiship-backend
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: pull, build, restart via PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            cd dockiship-backend

            # Pull latest
            git pull --ff-only

            # Install deps cleanly
            npx ci --no-audit --no-fund

            # Build (uses local devDependency)
            npx nest build

            # Restart with PM2 (start if missing)
            pm2 restart dockiship-backend
            pm2 save