name: Deploy DockiShip Backend (PM2)

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: deploy-dockiship-backend
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            .
          target: dockiship-backend   # resolves to ~/dockiship-backend
          strip_components: 0

      - name: Build, migrate, and restart (PM2 via nvm)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            # Load nvm for non-interactive shell
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            # Ensure Node 20 (no sudo) and use it
            nvm install 20
            nvm use 20

            cd ~/dockiship-backend

            # Load env for tooling (DATABASE_URL, etc.)
            if [ -f ".env" ]; then
              set -a; . ./.env; set +a
            fi

            # Install deps & build
            npm ci
            npm run build
            npm prune --omit=dev || true

            # Migrations (Prisma first, then TypeORM fallbacks)
            if [ -d "prisma" ] && [ -f "node_modules/.bin/prisma" ]; then
              echo "Running Prisma migrations..."
              npx prisma migrate deploy
            elif npm run | grep -qE "typeorm:migrate"; then
              echo "Running TypeORM migrations via 'typeorm:migrate'..."
              npm run typeorm:migrate
            elif npm run | grep -qE "migration:run"; then
              echo "Running TypeORM migrations via 'migration:run'..."
              npm run migration:run
            else
              echo "No migration step detected. Skipping."
            fi

            # PM2 managed start/reload
            if [ -f "ecosystem.config.js" ]; then
              pm2 startOrReload ecosystem.config.js --update-env
            else
              pm2 start dist/main.js --name dockiship-backend || pm2 restart dockiship-backend
            fi

            pm2 save
